project:
  type: website

website:
  title: "smouksassi.github.io"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com//smouksassi
      - icon: twitter
        href: https://x.com/poppkpd
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

editor: visual
execute:
  freeze: auto

