{
  "hash": "69a3c9c26107b52257c7311f9fc11ca3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Applications of the Delta Method in Pharmacometrics\"\nauthor: \"Samer Mouksassi\"\ndate: \"2025-12-01\"\ncategories: [Methods, visualization, uncertainty]\nimage: \"qivshdi.png\"\nformat:\n html:\n  code-fold: true\n---\n\nIn pharmacometrics models we often have model parameters modeled as a function of one or multiple covariates:\n\n\n$$CL = \\color{blue}{POPCL}\\times\\left(\\frac {\\color{green}{Weight}} {70}\\right)^\\color{blue}{dWTdCL}\\times\\left(\\frac{\\color{green}{Age}}{\\color{green}{Age} + \\color{blue}{Age50}}\\right)\\times e^{\\color{red}\\eta\\color{red}{CL}}$$\n\nIn this example the parameter clearance (CL) has two covariates effects:\n\n-   A continuous covariate power model of body weight (Weight) with a reference value of 70 (kg)\n\n-   A continuous covariate emax/hill maturation model as a function of Age.\n\nThe last term denotes the individual deviations from the population (random effects) which assumes that the population CL is log normally distributed.\n\nCommon software will estimate the fixed and random effects variances and provide the associated standard errors. For example we would get POPCL = 5 ± 0.25 L/h and the Sex effect is 0.18 ± 0.05 resulting in a Clearance of 5 × exp(0.18) = 5.99 L/h in men. What would be its standard error?\n\nAlso, we often want to report the [CV%](https://www.page-meeting.org/wp-content/uploads/pdf_assets/4964-Elassaiss-Schaap%20-%20Equations%20variability%20reporting%20PK-PD%20-%20Final.pdf) of the log normal distribution expressed as:\n\n$$CV(\\%)=\\sqrt{\\left(e^{\\omega^2}-1\\right)}$$ Again, what would be the standard error of the CV%?\n\nThe delta method is a statistical technique to approximate the standard error of a function of an estimator, such as a ratio or the log odds ratio or the inverse logit of a constrained parameter, using a first-order Taylor series expansion. It's especially useful when the function involves more than one parameter and/or the equation is complex such as there is no straightforward analytically computed solution. It relies on the original variable(s), the function form and the partial derivative of the function with respect to the parameters and the variance covariance matrix of the involved parameters. It has been used in multiple fields, including pharmacometrics, that the delta method matches the gold standard (simulation with uncertainty) even with [longitudinal model based meta-analysis (MBMA) nonlinear models](https://www.page-meeting.org/wp-content/uploads/pdf_assets/6769-Poster_PAGE_2012_MegBennetts.pdf). Also, in this important paper from the FDA entitled [Clarification on Precision Criteria to Derive Sample Size When Designing Pediatric Pharmacokinetic Studies](https://accp1.onlinelibrary.wiley.com/doi/10.1177/0091270011422812) R code to compute the delta method for derived variables was provided in **APPENDIX 3. R code for delta method to estimate standard error for a derived variable:**\n\n$$log(CL) = \\color{blue}{3.7421} + \\color{blue}{1.0078}\\times\\left( \\frac { \\color{green}{Weight}} {70}\\right)+log\\left(\\color{green}{Age}/(\\color{green}{Age}+4.8422)\\right)$$\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# Assume covariate model CL=theta1*(wt/70)** theta2*age/(age+theta3) and\n# Log of CL was modeled as LCL=thetap1+theta2*(wt/70)+log(age/(age+theta3))\n#input parameter estimates\n thetap1=3.7421\n theta2=1.0078\n theta3=4.8422\n#input variance-covariance matrix for the 3 parametersabove\n covp3=matrix(\n   c(0.29810, 0.05782, 1.27120,\n     0.05782, 0.02921, 0.02073,\n     1.27120, 0.02073, 8.42210),\n   nrow=3, byrow=T)\n  #define the weight and age combination for SE estima-tion\n wt=14\n age=3\n #define covariate model in R\n f <- function(x,y,z) x + y*log(wt/70) + log(age/(age+z))\n df<- deriv(body(f), c(\"x\",\"y\",\"z\"))\n x=thetap1\n y=theta2\n z=theta3\n out=eval(df)\n dfout=attr(out,\"gradient\")\n varlcl=dfout%*%covp3%*%t(dfout)\nSElcl=sqrt(varlcl)\nSElcl\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           [,1]\n[1,] 0.09436884\n```\n\n\n:::\n:::\n\n\nThe code above works, but it is easier to use the R package [msm](https://cran.r-project.org/web/packages/msm/index.html) which has a streamlined general `deltamethod` function of which I have a copy in my own package [coveffectsplot](https://smouksassi.github.io/coveffectsplot/reference/deltamethod.html). The only difference in mine is explicitly adding the evaluation environment which was necessary for the function to properly work in an R Shiny App. The `deltamethod` function source code:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\ndeltamethod <-  function (g, mean, cov, ses = TRUE, envir = parent.frame()) \n{\n    cov <- as.matrix(cov)\n    n <- length(mean)\n    if (!is.list(g)) \n        g <- list(g)\n    if ((dim(cov)[1] != n) || (dim(cov)[2] != n)) \n        stop(paste(\"Covariances should be a \", n, \" by \", n, \n            \" matrix\"))\n    syms <- paste(\"x\", 1:n, sep = \"\")\n    for (i in 1:n) assign(syms[i], mean[i])\n    gdashmu <- t(sapply(g, function(form) {\n        as.numeric(attr(eval(deriv(form, syms)), \"gradient\"))\n    }))\n    new.covar <- gdashmu %*% cov %*% t(gdashmu)\n    if (ses) {\n        new.se <- sqrt(diag(new.covar))\n        new.se\n    }\n    else new.covar\n}\n```\n:::\n\n\nI load `coveffectsplot` and use the `deltamethod` function to recompute SElcl exactly matching the result above note how the function should refer to the parameters as x1, x2, ..., etc.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nlibrary(coveffectsplot)\n deltamethod (~ x1 + x2*log(wt/70) + log(age/(age+x3)),\n              c(thetap1,theta2,theta3), covp3) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.09436884\n```\n\n\n:::\n:::\n\n\nAs expected, I get the same answer = 0.09436884.\n\nI have used this function in several pediatric filings/approvals. One advantage of the `deltamethod` is that it can be very fast and suitable for interactive Shiny Application to compute confidence intervals around effects or hazard ratios for an example refer to this paper [Total Kidney Volume Is a Prognostic Biomarker of Renal Function Decline and Progression to End-Stage Renal Disease in Patients With Autosomal Dominant Polycystic Kidney Disease](https://pmc.ncbi.nlm.nih.gov/articles/PMC5678856/) that had a Shiny App deployed [here](https://pharmacometrics.shinyapps.io/KIreports/ \"Interactive Tool for Computation of Hazard Ratio According to eGFR, TKV and Age\"). This was part of the qualification of kidney volume as a [Drug Development Tool](https://pubmed.ncbi.nlm.nih.gov/29142972/) for which I will write a separate post in the future. The FDA review can be consulted at this [link](https://www.fda.gov/drugs/drug-development-tool-ddt-qualification-programs/reviews-qualification-biomarker-total-kidney-volume-studies-treatment-autosomal-dominant-polycystic).\n\nBack to the random effect variance expressed as CV% standard error we can use the same code and function to compute a standard error for a transformation of the original estimated variance:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n omegaCL<-  0.42\n covOMEGA=matrix( c(0.2),nrow=1, byrow=T)\n sqrt(exp(omegaCL)-1) # formula for CV of a log normal\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7224691\n```\n\n\n:::\n:::\n\n\nThe CV% is computed to be \\~72.2 % with a standard error of: 0.4710526\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n deltamethod (~  sqrt(exp(x1)-1), c(omegaCL), covOMEGA)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4710526\n```\n\n\n:::\n:::\n\n\nAnother approach, albeit more time consuming, is to simulate the distribution using enough n samples and then compute the CV% using its formula: sd(x)/mean(x) which will exactly match the analytical formula for this relatively simple case:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nset.seed(165413)\nomegaCL<-  0.42\netaCL<- exp(rnorm(10000000,mean=0,sd=0.42^0.5))\nsd(etaCL)/mean(etaCL)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7222556\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\nsqrt(exp(omegaCL)-1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7224691\n```\n\n\n:::\n:::\n\n\nWhat if we have a more complex random effect model? Say an inverse logit transformation to constrain a parameter like bioavailbility between 0 and 1? Let us explore it with simulation !\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nlibrary(ggridges)\nlibrary(ggplot2)\nset.seed(165413)\nFlogit <- 0.47\nFvalue<- exp(Flogit)/(1+exp(Flogit))\nomegaF <-  0.42\netaF <- rnorm(10000000,mean=0,sd=omegaF^0.5)\nset.seed(165413)\netaF2 <- rnorm(10000000,mean=0,sd=(10*omegaF)^0.5)\nFeta <- exp(Flogit+etaF)/(1+exp(Flogit+etaF))\nFeta2 <- exp(Flogit+etaF2)/(1+exp(Flogit+etaF2))\n```\n:::\n\n\nThe omegaF = 0.42 translates to a %CV of \\~23.5%\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n100*sd(Feta)/mean(Feta)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 23.51329\n```\n\n\n:::\n:::\n\n\nWhen we multiply the omegaF by 10 = 4.2 the %CV becomes \\~55.0%\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n100*sd(Feta2)/mean(Feta2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 55.04038\n```\n\n\n:::\n:::\n\n\nHow appropriate is this summary? let us look at the distribution:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nFdataframe <- rbind(\n  data.frame(Feta=Feta ,paramname=\"omegaF=0.42, CV%=23.5%\"),\n  data.frame(Feta=Feta2,paramname=\"omegaF=4.20, CV%=55.0%\"))\n\n  ggplot(data=Fdataframe, aes(\n  x      = Feta,\n  y      = paramname,\n  fill   = factor(..quantile..),\n  height = ..ndensity..)) +\n  stat_density_ridges(\n    geom=\"density_ridges_gradient\", calc_ecdf=TRUE,\n    quantile_lines=TRUE, rel_min_height=0.001, scale=0.9,\n    quantiles=c(0.05, 0.25, 0.5, 0.75, 0.95)) +\n  facet_wrap(~paramname,scales=\"free\")+\n  scale_fill_manual(\n    name=\"BSV Ranges\",\n    values=c(\"white\", \"#FF000050\", \"#FF0000A0\", \"#FF0000A0\", \"#FF000050\", \"white\"),\n    labels = c(\"(0, 0.05]\", \"(0.05, 0.25]\",\n               \"(0.25, 0.5]\", \"(0.5, 0.75]\",\n               \"(0.75, 0.95]\", \"(0.95, 1]\")) +\n  theme_bw(base_size = 16) +\n  theme(\n    legend.position = \"right\",\n    axis.text.y     = element_blank(),\n    axis.ticks.y    = element_blank(),\n    axis.title.y    = element_blank(),\n    axis.text.x=element_text(size=12),\n    axis.title.x=element_text(size=14)) +\n  scale_x_continuous(breaks=c(0,0.25,0.5,0.75,1))+\n  coord_cartesian(expand=FALSE)+\n  labs(x=\"F values with BSV\",\n       subtitle=\"F=ilogit(0.47 + etaF) where etaF ~ Normal(0,omegaF^0.5)\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nWe can now see that when omegaF is 0.42 the distribution is a bit skewed with one mode while when the omegaF is 4.2 the distribution becomes multi-modal with a \"weird\" concentration of mass at 0 and 1. How representative is to \"summarize\" such a distribution with a CV%? isn't it more useful to show the full distribution? This would help us in understanding the distribution shape and where will 50 or 90% of my patients be on the F scale. Another possible interval for highly skewed distribution are the highest density intervals which I will illustrate next using `ggdist`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggdist)\nlibrary(patchwork)\n\n qi_plot <-  ggplot(Fdataframe,\n         aes(y = paramname, x = Feta)) +\n  stat_halfeye(aes(fill = after_stat(level)),\n               point_interval = median_qi,\n               .width = c(.50, .95, 1)) +\n  scale_fill_brewer(na.translate = FALSE) +\n  labs(x=\"F=ilogit(0.47 + etaF) where etaF ~ Normal(0,omegaF^0.5)\",\n    subtitle = \"Quantile intervals\\n.width = c(.50, .95, 1), point_interval = median_qi\",\n    fill = \"interval\"\n  )+\nfacet_wrap(~paramname,scales=\"free\")+\n  theme_bw(base_size = 16) +\n  theme(\n    legend.position = \"right\",\n    axis.text.y     = element_blank(),\n    axis.ticks.y    = element_blank(),\n    axis.title.y    = element_blank(),\n    axis.text.x=element_text(size=12),\n    axis.title.x=element_text(size=14)) +\n  scale_x_continuous(breaks=c(0,0.25,0.5,0.75,1))+\n  coord_cartesian(expand=FALSE)\n\nhdi_plot  <-  ggplot(Fdataframe,\n         aes(y = paramname, x = Feta)) +\n  stat_halfeye(aes(fill = after_stat(level)),\n               point_interval = mode_hdci,\n               .width = c(.50, .95, 1)) +\n  scale_fill_brewer(na.translate = FALSE) +\n  labs(x=\"F=ilogit(0.47 + etaF) where etaF ~ Normal(0,omegaF^0.5)\",\n    subtitle = \"Highest Density Intervals\\n.width = c(.50, .95, 1), point_interval = mode_hdci\",\n    fill = \"interval\"\n  )+\nfacet_wrap(~paramname,scales=\"free\")+\n  theme_bw(base_size = 16) +\n  theme(\n    legend.position = \"right\",\n    axis.text.y     = element_blank(),\n    axis.ticks.y    = element_blank(),\n    axis.title.y    = element_blank(),\n    axis.text.x=element_text(size=12),\n    axis.title.x=element_text(size=14)) +\n  scale_x_continuous(breaks=c(0,0.25,0.5,0.75,1))+\n  coord_cartesian(expand=FALSE)  \n\nqi_plot/hdi_plot\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nNext I compute the 50% intervals separately: Quantile Intervals `median_qi`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nFdataframe %>%\n  group_by(paramname)%>%\n  median_qi(Feta, .width = c(0.5))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 7\n  paramname               Feta .lower .upper .width .point .interval\n  <chr>                  <dbl>  <dbl>  <dbl>  <dbl> <chr>  <chr>    \n1 omegaF=0.42, CV%=23.5% 0.615  0.508  0.712    0.5 median qi       \n2 omegaF=4.20, CV%=55.0% 0.615  0.286  0.864    0.5 median qi       \n```\n\n\n:::\n:::\n\n\nHighest Density Intervals: `mode_hdi` notice how we get multiple intervals one per mode for omegaF=4.20\n\n\n::: {.cell}\n\n```{.r .cell-code}\nFdataframe %>%\n  group_by(paramname)%>%\n  mode_hdi(Feta, .width = c(0.5))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 7\n  paramname               Feta .lower .upper .width .point .interval\n  <chr>                  <dbl>  <dbl>  <dbl>  <dbl> <chr>  <chr>    \n1 omegaF=0.42, CV%=23.5% 0.645 0.535  0.737     0.5 mode   hdi      \n2 omegaF=4.20, CV%=55.0% 0.989 0.0104 0.0982    0.5 mode   hdi      \n3 omegaF=4.20, CV%=55.0% 0.989 0.712  0.714     0.5 mode   hdi      \n4 omegaF=4.20, CV%=55.0% 0.989 0.717  1.000     0.5 mode   hdi      \n```\n\n\n:::\n:::\n\n\nHighest Density Intervals continuous: `mode_hdci`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nFdataframe %>%\n  group_by(paramname)%>%\n  mode_hdci(Feta, .width = c(0.5))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 7\n  paramname               Feta .lower .upper .width .point .interval\n  <chr>                  <dbl>  <dbl>  <dbl>  <dbl> <chr>  <chr>    \n1 omegaF=0.42, CV%=23.5% 0.645  0.535  0.737    0.5 mode   hdci     \n2 omegaF=4.20, CV%=55.0% 0.989  0.615  1.000    0.5 mode   hdci     \n```\n\n\n:::\n:::\n\n\nWhen a distribution is asymmetrical, multimodal and/or with an important mass at the boundaries the quantile, the highest density and the highest density continuous intervals will significantly differ. I highly recommend to plot the data and to provide multiple interval types for such distributions.\n\nIn this post I have shown several examples/applications of the delta method to compute confidence intervals for and important model statistic that is a function of one or more model parameters. I have also showed how to compute intervals around random effects distributions via simulations arguing that a single stat such as CV% is inappropriate for non-symmetrical and/or multi-modal distributions using an inverse logit transformation of bioavailibility (F) as an example.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}